In [7]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('pew.csv')

In [4]:
df.head()

,Weight variable recommended for use in all analyses,Unique ID,Former Religion Target Groups,Former Religion Target Groups_labels,Current Religion Target Groups,Current Religion Target Groups_labels,Converts,Converts_labels,Quota groups,Quota groups_labels,...,"Q.22h Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --Jewis","Q.22h Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --Jewis_labels","Q.22h2 Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --just","Q.22h2 Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --just_labels","Q.22i Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --an At","Q.22i Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --an At_labels","Q.22j Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --an Ag","Q.22j Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --an Ag_labels","Q.22l Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --a par","Q.22l Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --a par_labels"
0,weight,psraid,FRMREL2,NaN,CURREL2,NaN,CON11,NaN,group,NaN,...,q22h,NaN,q22h2,NaN,q22i,NaN,q22j,NaN,q22l,NaN
1,11.0,10000047.0,10000.0,CATHOLIC,100001.0,ATHEIST,1.0,Converts,1.0,"Group 1 - Raised Catholic, now unaffiliated",...,2.0,No,2.0,No,NaN,NaN,2.0,No,2.0,No
2,13.0,10000065.0,10000.0,CATHOLIC,100003.0,UNAFFILIATED WITH ANY PARTICULAR RELIGION,1.0,Converts,1.0,"Group 1 - Raised Catholic, now unaffiliated",...,2.0,No,NaN,NaN,2.0,No,2.0,No,2.0,No
3,37.0,10000070.0,10000.0,CATHOLIC,1.0,BAPTIST,1.0,Converts,2.0,"Group 2 - Raised Catholic, now affiliated with...",...,2.0,No,2.0,No,2.0,No,2.0,No,2.0,No
4,188.0,10000103.0,2.0,METHODIST,3.0,NONDENOMINATIONAL CHRISTIAN,1.0,Converts,4.0,"Group 4 - Raised in non-Catholic faith, now af...",...,2.0,No,1.0,Yes,2.0,No,2.0,No,2.0,No

In [5]:
df.columns

Index(['Weight variable recommended for use in all analyses', 'Unique ID',
       'Former Religion Target Groups', 'Former Religion Target Groups_labels',
       'Current Religion Target Groups',
       'Current Religion Target Groups_labels', 'Converts', 'Converts_labels',
       'Quota groups', 'Quota groups_labels',
       ...
       'Q.22h Please tell me which, if any, you have ever identified with at any point in your life?  Have you ever been --Jewis',
       'Q.22h Please tell me which, if any, you have ever identified with at any point in your life?  Have you ever been --Jewis_labels',
       'Q.22h2 Please tell me which, if any, you have ever identified with at any point in your life?  Have you ever been --just',
       'Q.22h2 Please tell me which, if any, you have ever identified with at any point in your life?  Have you ever been --just_labels',
       'Q.22i Please tell me which, if any, you have ever identified with at any point in your life?  Have you ever been --an At',
       'Q.22i Please tell me which, if any, you have ever identified with at any point in your life?  Have you ever been --an At_labels',
       'Q.22j Please tell me which, if any, you have ever identified with at any point in your life?  Have you ever been --an Ag',
       'Q.22j Please tell me which, if any, you have ever identified with at any point in your life?  Have you ever been --an Ag_labels',
       'Q.22l Please tell me which, if any, you have ever identified with at any point in your life?  Have you ever been --a par',
       'Q.22l Please tell me which, if any, you have ever identified with at any point in your life?  Have you ever been --a par_labels'],
      dtype='object', length=210)

In [10]:
df.index

RangeIndex(start=0, stop=2868, step=1)

In [11]:
df.values

array([['weight', 'psraid', 'FRMREL2', ..., nan, 'q22l', nan],
       ['11.0', '10000047.0', '10000.0', ..., 'No', '2.0', 'No'],
       ['13.0', '10000065.0', '10000.0', ..., 'No', '2.0', 'No'],
       ...,
       ['28.0', '90000718.0', '10000.0', ..., 'No', '2.0', 'No'],
       ['46.0', '90000730.0', '10000.0', ..., 'No', '2.0', 'No'],
       ['44.0', '90000777.0', '10000.0', ..., 'No', '2.0', 'No']],
      dtype=object)

In [13]:
New=pd.melt(
df,
id_vars=['Unique ID']

)

In [14]:
New.head()

    Unique ID                                           variable   value
0      psraid  Weight variable recommended for use in all ana...  weight
1  10000047.0  Weight variable recommended for use in all ana...    11.0
2  10000065.0  Weight variable recommended for use in all ana...    13.0
3  10000070.0  Weight variable recommended for use in all ana...    37.0
4  10000103.0  Weight variable recommended for use in all ana...   188.0

In [15]:
New

         Unique ID                                           variable   value
0           psraid  Weight variable recommended for use in all ana...  weight
1       10000047.0  Weight variable recommended for use in all ana...    11.0
2       10000065.0  Weight variable recommended for use in all ana...    13.0
3       10000070.0  Weight variable recommended for use in all ana...    37.0
4       10000103.0  Weight variable recommended for use in all ana...   188.0
...            ...                                                ...     ...
599407  90000547.0  Q.22l Please tell me which, if any, you have e...     NaN
599408  90000666.0  Q.22l Please tell me which, if any, you have e...     NaN
599409  90000718.0  Q.22l Please tell me which, if any, you have e...      No
599410  90000730.0  Q.22l Please tell me which, if any, you have e...      No
599411  90000777.0  Q.22l Please tell me which, if any, you have e...      No

[599412 rows x 3 columns]

In [16]:
df

,Weight variable recommended for use in all analyses,Unique ID,Former Religion Target Groups,Former Religion Target Groups_labels,Current Religion Target Groups,Current Religion Target Groups_labels,Converts,Converts_labels,Quota groups,Quota groups_labels,...,"Q.22h Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --Jewis","Q.22h Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --Jewis_labels","Q.22h2 Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --just","Q.22h2 Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --just_labels","Q.22i Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --an At","Q.22i Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --an At_labels","Q.22j Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --an Ag","Q.22j Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --an Ag_labels","Q.22l Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --a par","Q.22l Please tell me which, if any, you have ever identified with at any point in your life? Have you ever been --a par_labels"
0,weight,psraid,FRMREL2,NaN,CURREL2,NaN,CON11,NaN,group,NaN,...,q22h,NaN,q22h2,NaN,q22i,NaN,q22j,NaN,q22l,NaN
1,11.0,10000047.0,10000.0,CATHOLIC,100001.0,ATHEIST,1.0,Converts,1.0,"Group 1 - Raised Catholic, now unaffiliated",...,2.0,No,2.0,No,NaN,NaN,2.0,No,2.0,No
2,13.0,10000065.0,10000.0,CATHOLIC,100003.0,UNAFFILIATED WITH ANY PARTICULAR RELIGION,1.0,Converts,1.0,"Group 1 - Raised Catholic, now unaffiliated",...,2.0,No,NaN,NaN,2.0,No,2.0,No,2.0,No
3,37.0,10000070.0,10000.0,CATHOLIC,1.0,BAPTIST,1.0,Converts,2.0,"Group 2 - Raised Catholic, now affiliated with...",...,2.0,No,2.0,No,2.0,No,2.0,No,2.0,No
4,188.0,10000103.0,2.0,METHODIST,3.0,NONDENOMINATIONAL CHRISTIAN,1.0,Converts,4.0,"Group 4 - Raised in non-Catholic faith, now af...",...,2.0,No,1.0,Yes,2.0,No,2.0,No,2.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,442.0,90000547.0,10000.0,CATHOLIC,10000.0,CATHOLIC,NaN,Non-converts,6.0,"Group 6 - Non-converts, affiliated (i.e., rais...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2864,386.0,90000666.0,10000.0,CATHOLIC,10000.0,CATHOLIC,NaN,Non-converts,6.0,"Group 6 - Non-converts, affiliated (i.e., rais...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2865,28.0,90000718.0,10000.0,CATHOLIC,100003.0,UNAFFILIATED WITH ANY PARTICULAR RELIGION,1.0,Converts,1.0,"Group 1 - Raised Catholic, now unaffiliated",...,2.0,No,NaN,NaN,2.0,No,2.0,No,2.0,No
2866,46.0,90000730.0,10000.0,CATHOLIC,6.0,PENTECOSTAL,1.0,Converts,2.0,"Group 2 - Raised Catholic, now affiliated with...",...,2.0,No,2.0,No,2.0,No,2.0,No,2.0,No
2867,44.0,90000777.0,10000.0,CATHOLIC,1.0,BAPTIST,1.0,Converts,2.0,"Group 2 - Raised Catholic, now affiliated with...",...,2.0,No,2.0,No,2.0,No,2.0,No,2.0,No

In [17]:
df.shape

(2868, 210)

In [18]:
New.shape

(599412, 3)